name: cue
description: "Physics-first Flutter animations with a composable, timeline-driven API"
version: 0.1.3
homepage: https://github.com/Milad-Akarie/cue
topics: 
  - animation
  - motion
  - timeline
  - keyframes
  - effects

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  coverage: ^1.15.0
  flutter_lints: ^5.0.0
